### PR TITLE
Update Header.cs

### PR DESCRIPTION
**Pull request by SteAmeR**
As known there are some fields such as CreationTime, AccessTime, ModificationTime in a Lnk file structure. When the "long" data type values in these fields are out of range that the DateTimeOffset function can accept, the Header.cs class throws an exception, and then the process terminates. This fix was developed to this issue.

### CODE REVIEW

**Review by EricZimmerman — COMMENTED** [review]
so are these conditions generally an error? how often have you seen this? is this an anti-forensics technique, or just bad/damaged data?

**Comment by SteAmeR** [comment]
> so are these conditions generally an error? how often have you seen this? is this an anti-forensics technique, or just bad/damaged data?

I've actually seen it used in a malware attack. Malicious LNK file: https://www.virustotal.com/gui/file/26919d61ccd3b95253511d019e70c8e8a6f256000234d3cb62d30ac10ebcc099/detection

**Comment by SteAmeR** [comment]
Hi again, can you update on Nuget?

**Comment by EricZimmerman** [comment]
done 1.3.8

**Pull request merged**
