### PR TITLE
Upgrade to NET 5.0

### PR DESCRIPTION
**Pull request by Still34**
## Summary

This PR attempts to migrate the existing solution from .NETFX4.6 to .NET 5.0 for better compatibility against newer projects.

### CODE REVIEW

**Comment by EricZimmerman** [comment]
What are all the .Idea related items?

**Comment by Still34** [comment]
Rider artifacts. I could remove those from the checkout.

**Comment by EricZimmerman** [comment]
Please do and I'll take a look at the changes then.

**Comment by EricZimmerman** [comment]
not sure how i left this sit. im updating to .net 6 here in a few

**Pull request closed without merging**
